### ISSUE TITLE
Always get a Invalid project_id response

### ISSUE THREAD

**Issue by kwellman** [joshdholtz/Sentry-Android#1]
I've integrated the library in my app, but whenever it tries to send an error report it fails and logs the following line:

08-16 16:16:17.749: DEBUG/Sentry(14262): SendEvent - 400 Invalid project_id: u'4'

I've copied and pasted the sentry dsn from my sentry settings so I know it's valid.

I'm using sentry 6.0.4.

**Comment by Christophe31** [comment]
I changed my DNS/DSN (redeployed on a new server with sentry 8)
SendEvent - 400 {"error":"Invalid project_id: u'3'"}
while python/raven works on my instance.
 D/Sentry: URI - http://x:y@sentry.my_domain.net/3
 I/System.out: AsyncTask #5 calls detatch()
 D/Sentry: SendEvent - 400 {"error":"Invalid project_id: u'3'"}
 D/Sentry: Adding request - UUID

I used to init with also base domain but currently it return a CSRF failure.
