### ISSUE TITLE
Attach User context

### ISSUE THREAD

**Issue by fab1an** [joshdholtz/Sentry-Android#108]
Is there a way to attach user context like described here: https://docs.sentry.io/learn/context/#capturing-the-user

**Comment by marcomorain** [comment]
Hi Fabian,

You can use a SentryEventCaptureListener as described in the README to add extra info to an event. The user fields should be accessible on the event in the callback.

**Comment by marcomorain** [comment]
Oops - hit reply and close on my phone by accident.

**Comment by marcomorain** [comment]
Yup, in the beforeCapture callback you can call .setUser on the event builder to add user context.

**Comment by marcomorain** [comment]
Did you get this working @fab1an ?

**Comment by fab1an** [comment]
Didn't have time for testing yet, i'll report back.

**Comment by marcomorain** [comment]
Thanks @fab1an
