### ISSUE TITLE
Disable on Debug

### ISSUE THREAD

**Issue by fab1an** [joshdholtz/Sentry-Android#112]
Is there a way to prevent Sentry-Android from anything when `BuildConfig.DEBUG == true`?

**Comment by edenman** [comment]
@fab1an late to the party but fwiw, I just have a `MyApp.setupSentry()` method that gets called during `MyApp.onCreate()` and I just override it in `MyDebugApp.setupSentry()` and don't call super.

**Comment by joshdholtz** [comment]
@fab1an I think there may be a word missing your question 😇 What are you looking to do exactly?
