### ISSUE TITLE
UncaughtExceptionHandler doesn't add breadcrumbs to SentryEventBuilder

### ISSUE THREAD

**Issue by andrewheckford** [joshdholtz/Sentry-Android#114]
When Sentry-Android handles a runtime exception with its uncaughtExceptionHandler it doesn't appear to add any accumulated breadcrumbs to the event posted to the Sentry server, whereas manually caught exceptions posted with Sentry.captureException and Sentry.captureEvent do include breadcrumbs. 

Is there a reason why the uncaughtExceptionHandler omits breadcrumbs? It would be quite useful for determining the events leading up to a runtime crash.

Would it be possible to add this for uncaught exceptions in a future release?

I'm currently using Sentry-Android 1.5.2 in my app as this appears to be the latest I can get from jCenter.

**Comment by marcomorain** [comment]
Hi Andrew,
Thanks for reporting this. There is no reasson that breadcrumbs are not added. That's an oversight on my part. 

I'll gladly accept a patch for this. 

Marc

**Comment by andrewheckford** [comment]
Hi Marc,

Thanks for your quick response. Depending on my work schedules over the next few weeks I'll have a go at adding this. I'm somewhat of a GitHub newbie: I assume I fork your repo, and then submit a Pull Request back to you with my changes?

Many thanks,

Andrew.

**Comment by marcomorain** [comment]
Hi Andrew, I've a fix for this this evening - @joshdholtz want to kick off another release? 🚀
