### ISSUE TITLE
Ability to send more breadcrumbs?

### ISSUE THREAD

**Issue by edenman** [joshdholtz/Sentry-Android#117]
I'd really like to use breadcrumbs as a log of what happened leading up to the crash, but 10 breadcrumbs is a pretty narrow window of events.  Any chance this could be customized?  I can put together a PR if that would be helpful.

**Comment by marcomorain** [comment]
Hi @edenman sorry I'm only seeing this now.

tbh the current limit of 10 was plucked from the air.

What would be a better default?

I'll do a PR to make it configurable

**Comment by edenman** [comment]
@marcomorain awesome! 10 seems like a reasonable default to me.

**Comment by edenman** [comment]
...but after looking at the commit, i'm totally fine with 100 that you changed it to :)
