### ISSUE TITLE
Setting release in my app

### ISSUE THREAD

**Issue by akramShokri** [joshdholtz/Sentry-Android#120]
Hi
I need to `setRelease` in my code because for me release name is not neccessarily app version name. Currently the value which I set in `setRelease` method is overrided with sentry library. Would you please make this override optional or somehow managable in your future release?

Thanks.

**Comment by marcomorain** [comment]
Hi @akramShokri thanks for logging this - it's a bug.

To work around this you can use a listener when you initialise Sentry:

```Java
Sentry.setCaptureListener(new SentryEventCaptureListener() {
    @Override
    public SentryEventBuilder beforeCapture(SentryEventBuilder builder) {
        return builder.setRelease("my-release-version");
    }
});
```

I'll work on a fix also.

**Comment by akramShokri** [comment]
Thanks for the comment and for the fix.
I didn't get your comment on email (don't know why :\ ) until today that I checked this issue.
Thank you
