### ISSUE TITLE
Setting of environment

### ISSUE THREAD

**Issue by laurenceputra** [joshdholtz/Sentry-Android#123]
Currently I'm not able to set the environment of the app without making modifications to the library. Possible to expose a function to do that?

**Comment by marcomorain** [comment]
Hi @laurenceputra that sounds like a good addition to the library. We'd happily accept a PR if you have the time.

I would do it by putting a public method on the SentryEventBuilder class `setEnvironment(String env)`.

**Comment by MihaelIsaev** [comment]
Could someone please build a new version and upload it to jCenter?
I want to use environment feature https://github.com/joshdholtz/Sentry-Android/pull/124/commits/7a5ebc44a5a0b329e37ecd9005a83e11f350f3f5

**Comment by seljabali** [comment]
@joshdholtz?

**Comment by joshdholtz** [comment]
@MihaelIsaev @seljabali Popped out a new build for you (v1.6.1). Sorry about taking so long!

**Comment by seljabali** [comment]
Thank you @joshdholtz

**Comment by joshdholtz** [comment]
Not a problem ❤️
