### ISSUE TITLE
Is this library no longer the recommended way to upload Sentry events?

### ISSUE THREAD

**Issue by edenman** [joshdholtz/Sentry-Android#127]
I just noticed that my Android events in Sentry (uploaded from `sentry-android:1.6.0`) have a "This event was reported with an old version of the java SDK." warning that points here: https://docs.sentry.io/clients/java/?_ga=1.162696184.514520677.1487898468 which recommends using https://github.com/getsentry/raven-java

**Comment by joshdholtz** [comment]
@edenman Sentry does now have proper support for Android with their `raven-java` SDK. I was just informed of this today and will be properly documenting the README as well as writing a migration blog post. I will keep this issue open for other to see 👀 

Much love to all of the people that have used and supported this library over the years ❤️

**Comment by edenman** [comment]
https://blog.sentry.io/2017/06/12/new-java-sdk is the aforementioned blog post, although it looks like they switched to `sentry-java` and `sentry-android` which is a little confusing given the name of this repo.  Probably worth throwing a big "DEPRECATED" banner at the top of this project's README, but then I think you can probably close this out.
