### ISSUE TITLE
Publish the library in a Gradle repository

### ISSUE THREAD

**Issue by luiseduardobrito** [joshdholtz/Sentry-Android#26]
Working with JAR files is too hard when managing lots of apps at the same time. Is there any plans to add the library to some central Maven repository, such as jCenter or MVN Repository?

Tks!

**Comment by h0tk3y** [comment]
Vote up for this :+1:.

**Comment by WesleyWu** [comment]
+1

**Comment by joshdholtz** [comment]
I will see what I can do :grin: I haven't Androided in a while so I need to get my Android legs back. I am currently out of town for business but I will try to get this done next week.

**Comment by thebogusman** [comment]
:+1:

**Comment by luiseduardobrito** [comment]
Great! Some months ago I forked your repo some months ago and put it in my
private Gradle repo. I can help you with that, but I will need probably
some weeks to send you a pull request, as I'm also out of my town.


---
*Luis Eduardo Brito*
Engenharia de Computação
Universidade Estadual de Campinas (Unicamp)

Tel: +55 (19) 983 656 062
Website: http://luiseduardobrito.github.io

<http://gnu.org/>  <http://opendefinition.org/>

2015-12-10 11:43 GMT-02:00 thebogusman <notifications@github.com>:

**Comment by joshdholtz** [comment]
Thanks @luiseduardobrito! I will let you know if I need any help :blush: This week got crazy but I have no plans this weekend so I will take some time Saturday morning to drink some :coffee: and figure out this Gradle stuff :wink: 

Sorry again for taking so long everyone!

**Comment by luiseduardobrito** [comment]
Haha, christmas is coming and every developer on earth is overloaded with
work because of that.


---
*Luis Eduardo Brito*
Engenharia de Computação
Universidade Estadual de Campinas (Unicamp)

Tel: +55 (19) 983 656 062
Website: http://luiseduardobrito.github.io

<http://gnu.org/>  <http://opendefinition.org/>

2015-12-17 15:21 GMT-02:00 Josh Holtz <notifications@github.com>:

**Comment by joshdholtz** [comment]
Thanks for understanding :innocent: I run a small software consulting company so a lot of things often come up and interrupt me from doing things like this so I'm **ALWAYS** open to PRs... But I will try to get this one done myself since I need to learn this new fancy Android Studio and Gradle nonsense :santa:

**Comment by luiseduardobrito** [comment]
Same here, small brazilian mobile consulting, 10+ developers, the clients
go crazy this time of the year.

Also, in my fork I changed some stuff to use the latest sentry api version,
I can invite you to the private repo if you want to see, but there's a lot
of stuff that would not belong here, such as exporting logs directly to an
Elasticsearch instance, and using Retrofit
<https://github.com/square/retrofit> + GSON as the Rest Client for the
request.

Regards


---
*Luis Eduardo Brito*
Engenharia de Computação
Universidade Estadual de Campinas (Unicamp)

Tel: +55 (19) 983 656 062
Website: http://luiseduardobrito.github.io

<http://gnu.org/>  <http://opendefinition.org/>

2015-12-17 15:34 GMT-02:00 Josh Holtz <notifications@github.com>:

**Comment by joshdholtz** [comment]
Hey everyone! I think I got this up and working with Gradle. I don't have it submitted to jcentral yet but there are installation instructions in this PR #29 if you would like to give it a try when you get a chance :blush:

**Comment by joshdholtz** [comment]
Should be solved now because PR #29
