### ISSUE TITLE
Support for API 23

### ISSUE THREAD

**Issue by batraabhishek** [joshdholtz/Sentry-Android#28]
org.apache.http.client.HttpClient and other are classes are depreciated with API 23. How should this be handled? Currently I am using OKHttp to make Sentry work with API 23.

**Comment by joshdholtz** [comment]
@batraabhishek Thanks for letting me know! My goal was to not bundle this library with any dependencies so I will look into this next week.

**Comment by Christophe31** [comment]
For now, in my app which had same problem at compile time, I added a dependency:
'cz.msebera.android:httpclient:4.4.+'
and then, just updated the domains imports…

**Comment by joshdholtz** [comment]
@batraabhishek @Christophe31 This should be solved with PR #29 that I just created. This is my first Gradle project repo thing I have created so if you could let me know if this works for you that would be great :blush:

**Comment by joshdholtz** [comment]
Should be solved now because PR #29
