### ISSUE TITLE
Send full stack trace

### ISSUE THREAD

**Issue by ftp27** [joshdholtz/Sentry-Android#32]
I added your library to my project and now I receive errors, but there is not enough information. How can I configure library for sending full stack trace?

**Comment by Christophe31** [comment]
Personally, with just default init setup, I have stack trace… If you're used to python, indeed, you don't get local vars, but that's still great for debugging.

I personally add some extra info (android version of current device, if error come from my background service or from my ui, the last update date of my app…).

As there are no local vars, the stack trace display is way easier.

By default, it only show the lines of the stack in your own app, if there is only one, it may show this only line… you may want to check to display hidden line or show raw stack.

Best reguards.

**Comment by joshdholtz** [comment]
@ftp27 There is not enough information in your description form me to help you out :wink: Can you tell me or copy in what kind of errors you are getting? If you get me that info I would be glad to help you out :blush: 

## How to catch errors (taken from top of README)
>Below is an example of how to register Sentry-Android to handle uncaught exceptions

```xml
<!-- REQUIRED to send captures to Sentry -->
<uses-permission android:name="android.permission.INTERNET" />
```

```java
public class MainActivity extends Activity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Sentry will look for uncaught exceptions from previous runs and send them        
        Sentry.init(this.getApplicationContext(), "YOUR-SENTRY-DSN");

    }

}
```

**Comment by joshdholtz** [comment]
Closing this issue for now because no response :innocent:
