### ISSUE TITLE
Application in the manifest and minSdkVersion 15 makes it difficult to import the lib.

### ISSUE THREAD

**Issue by ddello32** [joshdholtz/Sentry-Android#35]
By setting the minSdkVersion to 15 in the build.gradle file with no need, you limit the backwards compatibility of the lib. If you remove the unused appCompat dependency you can drop the minSdkVersion to 3.

Also the application tag in the lib's manifest file makes manifest merger harder. There's no need to declare an application tag, it tries to declare the allowBackup and label fields for the importing application this way.

**Comment by joshdholtz** [comment]
Thanks @ddello32! I will take a look into dropping back the version and removing the application tag :blush:

**Comment by joshdholtz** [comment]
Thanks for doing this, @ddello32 :heart:
