### ISSUE TITLE
[feature] Add Android build version

### ISSUE THREAD

**Issue by Christophe31** [joshdholtz/Sentry-Android#39]
As suggested, it would be nice to add android version by default.

https://github.com/joshdholtz/Sentry-Android/pull/34#issuecomment-194209572

I don't know if it should be a tag or what name it should use, but whatever, it's interesting data ;-).

**Comment by joshdholtz** [comment]
Thanks @Christophe31! I don't know why I didn't include that by default but I know how to handle this :wink:

**Comment by marcomorain** [comment]
@joshdholtz this was closed via https://github.com/joshdholtz/Sentry-Android/pull/61

**Comment by Christophe31** [comment]
indeed, I'll close this issue and thanx for the contrib!
