### ISSUE TITLE
Promote SentryEventCaptureListener as Interface

### ISSUE THREAD

**Issue by tlvenn** [joshdholtz/Sentry-Android#42]
Hi,

I don't really understand why SentryEventCaptureListener is an abstract class rather than an interface. It would be more convenient to promote it to an interface.

**Comment by joshdholtz** [comment]
I honestly don't really understand why it is an abstract class either 😇  Its been years since I've written this so I don't really have an answer for you but I can make that change as it seems reasonable.

**Comment by tlvenn** [comment]
Great thanks @joshdholtz, happy to provide the PR for this if needed
