### ISSUE TITLE
Add addTag / addExtra to the builder API

### ISSUE THREAD

**Issue by tlvenn** [joshdholtz/Sentry-Android#43]
Pretty much anything that is needed to keep a fluent API is already done but if I need to add a tag or a meta, it breaks.

The builder should expose 2 methods such as:

addTag(String key, String value)
addMeta(String key, String value)

**Comment by joshdholtz** [comment]
Thanks for the suggestion! I can work on adding this in.

**Comment by tlvenn** [comment]
@joshdholtz Happy to provide a PR if you want
