### ISSUE TITLE
minSdkVersion of library

### ISSUE THREAD

**Issue by VAdaihiep** [joshdholtz/Sentry-Android#44]
I have an issue: When add Sentry-Android to build.gradle, it show error minSDK of Sentry-Android is 15 and minSDK of my module is 14.

As I see in https://github.com/joshdholtz/Sentry-Android/blob/master/sentry-android/build.gradle, the minSdkVersion is 3, i don't know why Android studio show this error. Maybe the cause is when you deploy Sentry-Android, it take minSDKVersion from here https://github.com/joshdholtz/Sentry-Android/blob/master/app/build.gradle

So please configure library to resolve this issue. Thanks in advance.

**Comment by joshdholtz** [comment]
Hey @VAdaihiep! Sorry about the issue. I may have not pushed the latest version to gradle yet. I will take a look at doing that later today for you when I get back to my computer that can actually do that push 😊

**Comment by joshdholtz** [comment]
This should be solved with latest `1.4.0` push
