### ISSUE TITLE
How to use Tags?

### ISSUE THREAD

**Issue by Hunter712** [joshdholtz/Sentry-Android#48]
How to use Tags?

**Comment by Christophe31** [comment]
Here How I did:

        Sentry.init(ctx,
                    ctx.getString(R.string.sentry_host),
                    ctx.getString(R.string.sentry_dsn));
        Sentry.setCaptureListener(new Sentry.SentryEventCaptureListener() {
            @Override
            public Sentry.SentryEventBuilder beforeCapture(Sentry.SentryEventBuilder builder) {
                try {
                    builder.getExtra().put("name", config.deviceName);
                    builder.getTags().put("system_version", Build.VERSION.RELEASE);
                    builder.getTags().put("system_date", new Date(Build.TIME).toString());
               }
           }
       });

**Comment by joshdholtz** [comment]
Thanks for the reply, @Christophe31 😊  🙌   Closing this because not an issue and because there is also an example in the readme
