### ISSUE TITLE
Can you make the jar file available somewhere?

### ISSUE THREAD

**Issue by dgcooke** [joshdholtz/Sentry-Android#53]
Looking for the jar file as we do our own dependancy management

**Comment by joshdholtz** [comment]
@dgcooke There should be JAR file located here for you 😊  https://bintray.com/joshdholtz/maven/sentry-android/1.4.0/view#files/com/joshdholtz/sentry/sentry-android/1.4.0

I can put a link to this in each release in the future 😉

**Comment by will-emmerson** [comment]
I am also needing this, the jar file is not available at that link. There are javadocs, sources and an aar but not jar.
