### ISSUE TITLE
Contexts is serialized to wrong json type in API < 19

### ISSUE THREAD

**Issue by zerda** [joshdholtz/Sentry-Android#69]
At [SentryEventRequest](https://github.com/joshdholtz/Sentry-Android/blob/master/sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java#L666), we use `new JSONObject(builder.event).toString()` to get the JSON string. 

It is worked well in API 19, I have reformatted the result to make itself clear.
```json
{
    "contexts": {
        "os": {
            "type": "os",
            "build": "19",
            "kernel_version": "3.10.35+",
            "name": "Android",
            "version": "4.4.2"
        }
    }
}
```
but in API 17, the `contexts` member has been serialized to a String, not a JSONArray.
```json
{
    "contexts": "{ os={ build=17, type=os, kernel_version=3.4.5, version=4.2.2, name=Android } }"
}
```

**Comment by marcomorain** [comment]
pr incoming

**Comment by zerda** [comment]
I've tested this pr on an API 17 device, it works well. Thank you, @marcomorain
