### ISSUE TITLE
[Feature Request] Support for Stacktrace

### ISSUE THREAD

**Issue by jschamburger** [joshdholtz/Sentry-Android#81]
Hi,
thanks for this awesome library! It works very well and is really easy to set up.
It would be great to add support for capturing stacktraces **without** capturing an exception. 
I believe the stacktrace is always important to gain some knowledge about the context of an issue, but attaching an artificial to an event is a possible workaround, but not the best option since every event is then shown with title "Throwable" and the actual message is only displayed in the subtitle in Sentry.
I've seen an example of the stacktrace object here: https://gist.github.com/umurkontaci/9270201

Of course, I could just extend the SentryEventBuilder, but since the event is private, this does not seem like a viable option just for adding an additional field. Making the event protected should allow to extend the SentryEventBuilder quite easily, so this would already be helpful I guess.

Kind regards
Johannes

**Comment by jschamburger** [comment]
Nice! Thanks for the quick implementation of this feature!

**Comment by marcomorain** [comment]
You're welcome!
